/*!
 * @file CosmicRaySource.h
 * @brief Encapsulation of a source of cosmic rays (extended field of view)
 * @author Segev BenZvi
 * @date 15 Nov 2012
 * @version $Id: CosmicRaySource.h 23950 2015-02-05 21:04:49Z sybenzvi $
 */

#ifndef GRMODEL_SERVICES_SPECTRA_COSMICRAYSOURCE_H_INCLUDED
#define GRMODEL_SERVICES_SPECTRA_COSMICRAYSOURCE_H_INCLUDED

#include <grmodel-services/spectra/FluxSource.h>

#include <data-structures/physics/Particle.h>
#include <data-structures/time/ModifiedJulianDate.h>

#include <rng-service/RNGService.h>

class PowerLaw;

/*!
 * @class CosmicRaySource
 * @author Segev BenZvi
 * @date 15 Nov 2012
 * @ingroup gr_models
 * @brief Virtual base class for cosmic ray sources with a particle type and a
 *        spectrum in  units of 1/(length<sup>2</sup> time energy steradian).
 */
class CosmicRaySource : public FluxSource {

  public:

    CosmicRaySource() { }

    virtual ~CosmicRaySource() { }

    /// Get the source flux at a given energy
    virtual double GetFlux(const double E, const ModifiedJulianDate& mjd) const = 0;

    /// Get the weight which converts a PowerLaw (or PowerLaw-derived flux) to
    /// this flux
    virtual double GetFluxWeight(const double E, const ModifiedJulianDate& mjd, const PowerLaw& p) const = 0;

    /// Minimum energy (modeled or measured) of particles from the source
    virtual double GetMinEnergy() const = 0;

    /// Maximum energy (modeled or measured) of particles from the source
    virtual double GetMaxEnergy() const = 0;

    /// Randomly sample an energy from the source spectrum in [E0, E1]
    virtual double GetRandomEnergy(const RNGService& rng,
                                   const double E0, const double E1) const = 0;

    /// Integrate the source spectrum between two energies
    virtual double Integrate(const double E0, const double E1,
                             const ModifiedJulianDate& mjd) const = 0;

    /// Get the particle type generated by the source
    const ParticleType& GetParticleType() const { return particleType_; }

};

#endif // GRMODEL_SERVICES_SPECTRA_COSMICRAYSOURCE_H_INCLUDED

